FROM linuxbrew/brew

# required to be passed in
ARG SERVICE_PATH
ARG INSTALL_PATH=/lambda-ruby
ARG LOCAL_USER=lambda-ruby

# Install taps
RUN brew tap aws/tap; \
brew install awscli aws-sam-cli node

# Install Serverless
#RUN npm i -g serverless@1.52.0

# Install Ruby and bundler for sam build
RUN apt-add-repository ppa:brightbox/ruby-ng
RUN apt-get update
RUN apt-get install -y ruby2.5
RUN gem install bundler --no-ri --no-rdoc

# Create a directory where our app will be placed
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH
