# rails new appname --skip-yarn --skip-git --skip-action-cable --skip-coffee --skip-turbolinks --skip-test --skip-system-test --api

FROM ruby:2.5.0
RUN apt-get update -qq && apt-get install -y build-essential nodejs vim sudo

# required to be passed in
ARG APP_PATH

ARG INSTALL_PATH=/app
ARG LOCAL_USER=rails

# Create a directory where our app will be placed
RUN mkdir -p $INSTALL_PATH

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# Create local user
RUN useradd -m $LOCAL_USER && echo "${LOCAL_USER}:${LOCAL_USER}" | chpasswd && adduser $LOCAL_USER sudo
USER $LOCAL_USER

COPY . $INSTALL_PATH

CMD ["rails", "server"]
