# rails new famoustabi --skip-yarn --skip-git --skip-action-cable --skip-coffee --skip-turbolinks --skip-test --skip-system-test --api
# jets new demo --mode api --database=postgresql

FROM ruby:2.5.0

RUN apt-get update -qq && apt-get install -y build-essential nodejs vim sudo
RUN apt-get install -y rsync yarn unzip zip # needed for jets

# required to be passed in
ARG APP_PATH

ARG INSTALL_PATH=/app
ARG LOCAL_USER=rails

# Create a directory where our app will be placed
RUN mkdir -p $INSTALL_PATH

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

RUN gem install jets --no-ri --no-rdoc

COPY $APP_PATH/Gemfile .
COPY $APP_PATH/Gemfile.lock .
RUN bundle install

# Create local user
RUN useradd -m $LOCAL_USER && echo "${LOCAL_USER}:${LOCAL_USER}" | chpasswd && adduser $LOCAL_USER sudo
USER $LOCAL_USER

COPY . $INSTALL_PATH

CMD ["bundle", "exec", "jets", "server"]
